version: 0.0
os: linux
files:
  - source: /vendor/
    destination: /home/ec2-user/serverpod/upload/vendor/
  - source: /guide_infra_ui_server/
    destination: /home/ec2-user/serverpod/upload/guide_infra_ui_server/
hooks:
  BeforeInstall:
    - location: guide_infra_ui_server/aws/scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: guide_infra_ui_server/aws/scripts/start_server
      timeout: 300
      runas: root
