const N3_VOCAB = [
  // Nouns - Daily Life
  { kanji: "経験", reading: "けいけん", meaning: "experience", example: "いい経験になった。", category: "noun" },
  { kanji: "習慣", reading: "しゅうかん", meaning: "habit, custom", example: "毎朝走る習慣がある。", category: "noun" },
  { kanji: "予定", reading: "よてい", meaning: "plan, schedule", example: "明日の予定は何ですか。", category: "noun" },
  { kanji: "関係", reading: "かんけい", meaning: "relationship, connection", example: "彼とは関係がない。", category: "noun" },
  { kanji: "場合", reading: "ばあい", meaning: "case, situation", example: "その場合は連絡してください。", category: "noun" },
  { kanji: "理由", reading: "りゆう", meaning: "reason", example: "理由を教えてください。", category: "noun" },
  { kanji: "意見", reading: "いけん", meaning: "opinion", example: "意見を聞かせてください。", category: "noun" },
  { kanji: "事実", reading: "じじつ", meaning: "fact, truth", example: "それは事実です。", category: "noun" },
  { kanji: "目的", reading: "もくてき", meaning: "purpose, goal", example: "旅行の目的は何ですか。", category: "noun" },
  { kanji: "原因", reading: "げんいん", meaning: "cause, origin", example: "事故の原因を調べる。", category: "noun" },
  { kanji: "結果", reading: "けっか", meaning: "result", example: "試験の結果が出た。", category: "noun" },
  { kanji: "準備", reading: "じゅんび", meaning: "preparation", example: "準備ができました。", category: "noun" },
  { kanji: "状態", reading: "じょうたい", meaning: "condition, state", example: "健康な状態を保つ。", category: "noun" },
  { kanji: "種類", reading: "しゅるい", meaning: "type, kind", example: "どんな種類がありますか。", category: "noun" },
  { kanji: "割合", reading: "わりあい", meaning: "ratio, percentage", example: "男女の割合は半々です。", category: "noun" },
  { kanji: "影響", reading: "えいきょう", meaning: "influence, effect", example: "環境に影響を与える。", category: "noun" },
  { kanji: "印象", reading: "いんしょう", meaning: "impression", example: "第一印象が大切だ。", category: "noun" },
  { kanji: "期間", reading: "きかん", meaning: "period, term", example: "試用期間は三ヶ月です。", category: "noun" },
  { kanji: "記念", reading: "きねん", meaning: "commemoration, memorial", example: "記念写真を撮ろう。", category: "noun" },
  { kanji: "規則", reading: "きそく", meaning: "rule, regulation", example: "規則を守ってください。", category: "noun" },
  { kanji: "基本", reading: "きほん", meaning: "basics, foundation", example: "基本が大切です。", category: "noun" },
  { kanji: "共通", reading: "きょうつう", meaning: "common, shared", example: "共通の趣味がある。", category: "noun" },
  { kanji: "許可", reading: "きょか", meaning: "permission", example: "許可をもらう。", category: "noun" },
  { kanji: "景色", reading: "けしき", meaning: "scenery, view", example: "きれいな景色ですね。", category: "noun" },
  { kanji: "効果", reading: "こうか", meaning: "effect, result", example: "この薬は効果がある。", category: "noun" },

  // Nouns - Society & Work
  { kanji: "社会", reading: "しゃかい", meaning: "society", example: "社会に貢献する。", category: "noun" },
  { kanji: "政治", reading: "せいじ", meaning: "politics", example: "政治に興味がある。", category: "noun" },
  { kanji: "経済", reading: "けいざい", meaning: "economy", example: "経済が成長している。", category: "noun" },
  { kanji: "産業", reading: "さんぎょう", meaning: "industry", example: "日本の産業は発展した。", category: "noun" },
  { kanji: "技術", reading: "ぎじゅつ", meaning: "technology, skill", example: "最新の技術を使う。", category: "noun" },
  { kanji: "収入", reading: "しゅうにゅう", meaning: "income", example: "収入が増えた。", category: "noun" },
  { kanji: "責任", reading: "せきにん", meaning: "responsibility", example: "責任を取る。", category: "noun" },
  { kanji: "条件", reading: "じょうけん", meaning: "condition, requirement", example: "条件に合う仕事を探す。", category: "noun" },
  { kanji: "制度", reading: "せいど", meaning: "system, institution", example: "新しい制度を作る。", category: "noun" },
  { kanji: "対象", reading: "たいしょう", meaning: "target, object", example: "調査の対象は学生だ。", category: "noun" },
  { kanji: "地域", reading: "ちいき", meaning: "area, region", example: "この地域は安全です。", category: "noun" },

  // Nouns - Nature & Science
  { kanji: "環境", reading: "かんきょう", meaning: "environment", example: "環境を守ろう。", category: "noun" },
  { kanji: "温度", reading: "おんど", meaning: "temperature", example: "温度が上がった。", category: "noun" },
  { kanji: "地震", reading: "じしん", meaning: "earthquake", example: "大きな地震があった。", category: "noun" },
  { kanji: "材料", reading: "ざいりょう", meaning: "material, ingredient", example: "料理の材料を買う。", category: "noun" },
  { kanji: "性質", reading: "せいしつ", meaning: "nature, property", example: "水の性質を調べる。", category: "noun" },

  // I-adjectives
  { kanji: "激しい", reading: "はげしい", meaning: "intense, fierce", example: "激しい雨が降った。", category: "i-adjective" },
  { kanji: "恥ずかしい", reading: "はずかしい", meaning: "embarrassing, shy", example: "恥ずかしくて言えない。", category: "i-adjective" },
  { kanji: "素晴らしい", reading: "すばらしい", meaning: "wonderful, splendid", example: "素晴らしい景色だ。", category: "i-adjective" },
  { kanji: "悔しい", reading: "くやしい", meaning: "regrettable, frustrating", example: "負けて悔しい。", category: "i-adjective" },
  { kanji: "羨ましい", reading: "うらやましい", meaning: "envious, jealous", example: "あなたが羨ましい。", category: "i-adjective" },
  { kanji: "詳しい", reading: "くわしい", meaning: "detailed, knowledgeable", example: "詳しく説明してください。", category: "i-adjective" },
  { kanji: "等しい", reading: "ひとしい", meaning: "equal", example: "二つの値は等しい。", category: "i-adjective" },
  { kanji: "鋭い", reading: "するどい", meaning: "sharp, keen", example: "鋭い目つきをしている。", category: "i-adjective" },
  { kanji: "幼い", reading: "おさない", meaning: "young, childish", example: "幼い子供がいる。", category: "i-adjective" },
  { kanji: "賢い", reading: "かしこい", meaning: "clever, wise", example: "賢い子供だ。", category: "i-adjective" },
  { kanji: "怪しい", reading: "あやしい", meaning: "suspicious, dubious", example: "怪しい人を見た。", category: "i-adjective" },
  { kanji: "苦しい", reading: "くるしい", meaning: "painful, difficult", example: "生活が苦しい。", category: "i-adjective" },
  { kanji: "貧しい", reading: "まずしい", meaning: "poor", example: "貧しい生活を送る。", category: "i-adjective" },
  { kanji: "親しい", reading: "したしい", meaning: "close, intimate", example: "親しい友人がいる。", category: "i-adjective" },
  { kanji: "正しい", reading: "ただしい", meaning: "correct, right", example: "正しい答えを選ぶ。", category: "i-adjective" },

  // Na-adjectives
  { kanji: "重大", reading: "じゅうだい", meaning: "serious, important", example: "重大な問題が起きた。", category: "na-adjective" },
  { kanji: "正確", reading: "せいかく", meaning: "accurate, precise", example: "正確な情報が必要だ。", category: "na-adjective" },
  { kanji: "適当", reading: "てきとう", meaning: "appropriate; careless", example: "適当に選んだ。", category: "na-adjective" },
  { kanji: "必要", reading: "ひつよう", meaning: "necessary", example: "パスポートが必要です。", category: "na-adjective" },
  { kanji: "不安", reading: "ふあん", meaning: "anxiety, uneasy", example: "将来が不安だ。", category: "na-adjective" },
  { kanji: "複雑", reading: "ふくざつ", meaning: "complex, complicated", example: "複雑な問題だ。", category: "na-adjective" },
  { kanji: "豊富", reading: "ほうふ", meaning: "abundant, rich", example: "経験が豊富だ。", category: "na-adjective" },
  { kanji: "明確", reading: "めいかく", meaning: "clear, definite", example: "明確な答えが欲しい。", category: "na-adjective" },
  { kanji: "有名", reading: "ゆうめい", meaning: "famous", example: "有名な歌手だ。", category: "na-adjective" },
  { kanji: "立派", reading: "りっぱ", meaning: "splendid, admirable", example: "立派な建物だ。", category: "na-adjective" },
  { kanji: "素直", reading: "すなお", meaning: "obedient, honest", example: "素直な子供だ。", category: "na-adjective" },
  { kanji: "丁寧", reading: "ていねい", meaning: "polite, careful", example: "丁寧に説明する。", category: "na-adjective" },
  { kanji: "熱心", reading: "ねっしん", meaning: "enthusiastic, eager", example: "熱心に勉強する。", category: "na-adjective" },
  { kanji: "貴重", reading: "きちょう", meaning: "precious, valuable", example: "貴重な経験だ。", category: "na-adjective" },
  { kanji: "深刻", reading: "しんこく", meaning: "serious, grave", example: "深刻な問題だ。", category: "na-adjective" },

  // Verbs - Group 1
  { kanji: "届く", reading: "とどく", meaning: "to reach, to arrive", example: "荷物が届いた。", category: "verb" },
  { kanji: "届ける", reading: "とどける", meaning: "to deliver", example: "書類を届ける。", category: "verb" },
  { kanji: "集まる", reading: "あつまる", meaning: "to gather (intransitive)", example: "人が集まった。", category: "verb" },
  { kanji: "集める", reading: "あつめる", meaning: "to collect (transitive)", example: "切手を集める。", category: "verb" },
  { kanji: "決まる", reading: "きまる", meaning: "to be decided", example: "日程が決まった。", category: "verb" },
  { kanji: "決める", reading: "きめる", meaning: "to decide", example: "旅行先を決める。", category: "verb" },
  { kanji: "変わる", reading: "かわる", meaning: "to change (intransitive)", example: "天気が変わった。", category: "verb" },
  { kanji: "変える", reading: "かえる", meaning: "to change (transitive)", example: "計画を変える。", category: "verb" },
  { kanji: "伝える", reading: "つたえる", meaning: "to convey, to tell", example: "気持ちを伝える。", category: "verb" },
  { kanji: "伝わる", reading: "つたわる", meaning: "to be conveyed", example: "気持ちが伝わった。", category: "verb" },
  { kanji: "続く", reading: "つづく", meaning: "to continue (intransitive)", example: "雨が続いている。", category: "verb" },
  { kanji: "続ける", reading: "つづける", meaning: "to continue (transitive)", example: "勉強を続ける。", category: "verb" },
  { kanji: "増える", reading: "ふえる", meaning: "to increase (intransitive)", example: "人口が増えた。", category: "verb" },
  { kanji: "増やす", reading: "ふやす", meaning: "to increase (transitive)", example: "収入を増やす。", category: "verb" },
  { kanji: "減る", reading: "へる", meaning: "to decrease (intransitive)", example: "体重が減った。", category: "verb" },
  { kanji: "減らす", reading: "へらす", meaning: "to decrease (transitive)", example: "費用を減らす。", category: "verb" },
  { kanji: "壊れる", reading: "こわれる", meaning: "to break (intransitive)", example: "パソコンが壊れた。", category: "verb" },
  { kanji: "壊す", reading: "こわす", meaning: "to break (transitive)", example: "おもちゃを壊す。", category: "verb" },
  { kanji: "片付ける", reading: "かたづける", meaning: "to tidy up", example: "部屋を片付ける。", category: "verb" },
  { kanji: "気付く", reading: "きづく", meaning: "to notice", example: "間違いに気付いた。", category: "verb" },

  // Verbs - Thinking & Communication
  { kanji: "考える", reading: "かんがえる", meaning: "to think, to consider", example: "よく考えてから答える。", category: "verb" },
  { kanji: "調べる", reading: "しらべる", meaning: "to investigate, to look up", example: "辞書で調べる。", category: "verb" },
  { kanji: "比べる", reading: "くらべる", meaning: "to compare", example: "二つの商品を比べる。", category: "verb" },
  { kanji: "確認", reading: "かくにん", meaning: "to confirm, confirmation", example: "予約を確認する。", category: "verb" },
  { kanji: "説明", reading: "せつめい", meaning: "to explain, explanation", example: "詳しく説明してください。", category: "verb" },
  { kanji: "紹介", reading: "しょうかい", meaning: "to introduce, introduction", example: "友達を紹介する。", category: "verb" },
  { kanji: "相談", reading: "そうだん", meaning: "to consult, consultation", example: "先生に相談する。", category: "verb" },
  { kanji: "賛成", reading: "さんせい", meaning: "to agree, agreement", example: "その意見に賛成です。", category: "verb" },
  { kanji: "反対", reading: "はんたい", meaning: "to oppose, opposition", example: "計画に反対する。", category: "verb" },
  { kanji: "注意", reading: "ちゅうい", meaning: "to be careful, caution", example: "車に注意してください。", category: "verb" },

  // Verbs - Action
  { kanji: "参加", reading: "さんか", meaning: "to participate", example: "大会に参加する。", category: "verb" },
  { kanji: "利用", reading: "りよう", meaning: "to use, utilization", example: "図書館を利用する。", category: "verb" },
  { kanji: "発見", reading: "はっけん", meaning: "to discover, discovery", example: "新しい星を発見した。", category: "verb" },
  { kanji: "表現", reading: "ひょうげん", meaning: "to express, expression", example: "気持ちを表現する。", category: "verb" },
  { kanji: "成功", reading: "せいこう", meaning: "to succeed, success", example: "実験に成功した。", category: "verb" },
  { kanji: "失敗", reading: "しっぱい", meaning: "to fail, failure", example: "試験に失敗した。", category: "verb" },
  { kanji: "完成", reading: "かんせい", meaning: "to complete, completion", example: "作品が完成した。", category: "verb" },
  { kanji: "発展", reading: "はってん", meaning: "to develop, development", example: "経済が発展する。", category: "verb" },
  { kanji: "実現", reading: "じつげん", meaning: "to realize, realization", example: "夢を実現する。", category: "verb" },
  { kanji: "存在", reading: "そんざい", meaning: "to exist, existence", example: "問題が存在する。", category: "verb" },

  // Adverbs
  { kanji: "必ず", reading: "かならず", meaning: "certainly, without fail", example: "必ず来てください。", category: "adverb" },
  { kanji: "特に", reading: "とくに", meaning: "especially, particularly", example: "特に問題はない。", category: "adverb" },
  { kanji: "実は", reading: "じつは", meaning: "actually, in fact", example: "実は私も知らない。", category: "adverb" },
  { kanji: "確かに", reading: "たしかに", meaning: "certainly, surely", example: "確かにそうだ。", category: "adverb" },
  { kanji: "直接", reading: "ちょくせつ", meaning: "directly", example: "直接会って話す。", category: "adverb" },
  { kanji: "次々", reading: "つぎつぎ", meaning: "one after another", example: "問題が次々と起きた。", category: "adverb" },
  { kanji: "一般的", reading: "いっぱんてき", meaning: "generally", example: "一般的にそう言われている。", category: "adverb" },
  { kanji: "急に", reading: "きゅうに", meaning: "suddenly", example: "急に雨が降ってきた。", category: "adverb" },
  { kanji: "徐々に", reading: "じょじょに", meaning: "gradually", example: "徐々に上達した。", category: "adverb" },
  { kanji: "最も", reading: "もっとも", meaning: "most, extremely", example: "最も大切なことだ。", category: "adverb" },
  { kanji: "やはり", reading: "やはり", meaning: "as expected, after all", example: "やはり難しかった。", category: "adverb" },
  { kanji: "まさか", reading: "まさか", meaning: "no way, unbelievable", example: "まさかそんなことが。", category: "adverb" },
  { kanji: "たとえ", reading: "たとえ", meaning: "even if", example: "たとえ雨でも行く。", category: "adverb" },
  { kanji: "せっかく", reading: "せっかく", meaning: "with effort, specially", example: "せっかく来たのに。", category: "adverb" },
  { kanji: "なるべく", reading: "なるべく", meaning: "as much as possible", example: "なるべく早く来てください。", category: "adverb" },

  // Expressions & Grammar Words
  { kanji: "つまり", reading: "つまり", meaning: "in other words, that is", example: "つまり、賛成ですか。", category: "expression" },
  { kanji: "例えば", reading: "たとえば", meaning: "for example", example: "例えば、こんな方法がある。", category: "expression" },
  { kanji: "その結果", reading: "そのけっか", meaning: "as a result", example: "その結果、合格した。", category: "expression" },
  { kanji: "一方", reading: "いっぽう", meaning: "on the other hand", example: "一方、反対の意見もある。", category: "expression" },
  { kanji: "そのため", reading: "そのため", meaning: "therefore, for that reason", example: "そのため、遅れた。", category: "expression" },
  { kanji: "ところが", reading: "ところが", meaning: "however, but", example: "ところが、失敗した。", category: "expression" },
  { kanji: "それにしても", reading: "それにしても", meaning: "nevertheless, even so", example: "それにしても暑いですね。", category: "expression" },
  { kanji: "ようするに", reading: "ようするに", meaning: "in short, basically", example: "ようするに、ダメだった。", category: "expression" },
  { kanji: "ところで", reading: "ところで", meaning: "by the way", example: "ところで、明日は暇ですか。", category: "expression" },
  { kanji: "さすが", reading: "さすが", meaning: "as expected (of)", example: "さすがプロだ。", category: "expression" },

  // More Nouns - Feelings & Abstract
  { kanji: "気持ち", reading: "きもち", meaning: "feeling, mood", example: "気持ちを伝えたい。", category: "noun" },
  { kanji: "興味", reading: "きょうみ", meaning: "interest", example: "日本文化に興味がある。", category: "noun" },
  { kanji: "自信", reading: "じしん", meaning: "confidence", example: "自信を持って。", category: "noun" },
  { kanji: "我慢", reading: "がまん", meaning: "patience, endurance", example: "もう我慢できない。", category: "noun" },
  { kanji: "努力", reading: "どりょく", meaning: "effort", example: "努力が実を結んだ。", category: "noun" },
  { kanji: "勇気", reading: "ゆうき", meaning: "courage", example: "勇気を出して話した。", category: "noun" },
  { kanji: "夢中", reading: "むちゅう", meaning: "being absorbed in", example: "ゲームに夢中だ。", category: "noun" },
  { kanji: "記憶", reading: "きおく", meaning: "memory", example: "記憶力がいい。", category: "noun" },
  { kanji: "想像", reading: "そうぞう", meaning: "imagination", example: "想像以上に大きい。", category: "noun" },
  { kanji: "態度", reading: "たいど", meaning: "attitude", example: "態度が悪い。", category: "noun" },
  { kanji: "能力", reading: "のうりょく", meaning: "ability, capacity", example: "能力を発揮する。", category: "noun" },
  { kanji: "価値", reading: "かち", meaning: "value, worth", example: "価値がある本だ。", category: "noun" },
  { kanji: "常識", reading: "じょうしき", meaning: "common sense", example: "それは常識です。", category: "noun" },
  { kanji: "知識", reading: "ちしき", meaning: "knowledge", example: "知識を深める。", category: "noun" },
  { kanji: "表情", reading: "ひょうじょう", meaning: "facial expression", example: "嬉しそうな表情だ。", category: "noun" },

  // More Verbs
  { kanji: "向かう", reading: "むかう", meaning: "to head towards", example: "駅に向かう。", category: "verb" },
  { kanji: "通う", reading: "かよう", meaning: "to commute", example: "学校に通う。", category: "verb" },
  { kanji: "慣れる", reading: "なれる", meaning: "to get used to", example: "新しい生活に慣れた。", category: "verb" },
  { kanji: "育てる", reading: "そだてる", meaning: "to raise, to bring up", example: "子供を育てる。", category: "verb" },
  { kanji: "育つ", reading: "そだつ", meaning: "to grow up", example: "田舎で育った。", category: "verb" },
  { kanji: "輝く", reading: "かがやく", meaning: "to shine, to sparkle", example: "星が輝いている。", category: "verb" },
  { kanji: "叶える", reading: "かなえる", meaning: "to fulfill, to realize", example: "夢を叶える。", category: "verb" },
  { kanji: "込む", reading: "こむ", meaning: "to be crowded", example: "電車が込んでいる。", category: "verb" },
  { kanji: "叱る", reading: "しかる", meaning: "to scold", example: "子供を叱る。", category: "verb" },
  { kanji: "褒める", reading: "ほめる", meaning: "to praise", example: "先生に褒められた。", category: "verb" },
  { kanji: "断る", reading: "ことわる", meaning: "to refuse, to decline", example: "誘いを断る。", category: "verb" },
  { kanji: "頼む", reading: "たのむ", meaning: "to request, to ask", example: "友達に頼む。", category: "verb" },
  { kanji: "迷う", reading: "まよう", meaning: "to be lost, to hesitate", example: "道に迷った。", category: "verb" },
  { kanji: "諦める", reading: "あきらめる", meaning: "to give up", example: "夢を諦めない。", category: "verb" },
  { kanji: "驚く", reading: "おどろく", meaning: "to be surprised", example: "結果に驚いた。", category: "verb" },

  // More Na-adjectives
  { kanji: "自由", reading: "じゆう", meaning: "free, freedom", example: "自由な生活がしたい。", category: "na-adjective" },
  { kanji: "平和", reading: "へいわ", meaning: "peaceful, peace", example: "平和な世界を願う。", category: "na-adjective" },
  { kanji: "安全", reading: "あんぜん", meaning: "safe, safety", example: "安全な場所に避難する。", category: "na-adjective" },
  { kanji: "危険", reading: "きけん", meaning: "dangerous, danger", example: "危険な場所に行くな。", category: "na-adjective" },
  { kanji: "新鮮", reading: "しんせん", meaning: "fresh", example: "新鮮な魚を買う。", category: "na-adjective" },
  { kanji: "退屈", reading: "たいくつ", meaning: "boring, tedious", example: "退屈な授業だった。", category: "na-adjective" },
  { kanji: "夢中", reading: "むちゅう", meaning: "absorbed, crazy about", example: "サッカーに夢中だ。", category: "na-adjective" },
  { kanji: "真剣", reading: "しんけん", meaning: "serious, earnest", example: "真剣に取り組む。", category: "na-adjective" },
  { kanji: "素敵", reading: "すてき", meaning: "lovely, wonderful", example: "素敵なプレゼントだ。", category: "na-adjective" },
  { kanji: "得意", reading: "とくい", meaning: "good at, proud", example: "料理が得意です。", category: "na-adjective" },

  // More Nouns - Education & Health
  { kanji: "教育", reading: "きょういく", meaning: "education", example: "教育は大切だ。", category: "noun" },
  { kanji: "研究", reading: "けんきゅう", meaning: "research", example: "研究を続ける。", category: "noun" },
  { kanji: "実験", reading: "じっけん", meaning: "experiment", example: "科学の実験をする。", category: "noun" },
  { kanji: "健康", reading: "けんこう", meaning: "health", example: "健康が一番大切だ。", category: "noun" },
  { kanji: "治療", reading: "ちりょう", meaning: "treatment, medical care", example: "治療を受ける。", category: "noun" },
  { kanji: "症状", reading: "しょうじょう", meaning: "symptom", example: "症状が改善した。", category: "noun" },
  { kanji: "栄養", reading: "えいよう", meaning: "nutrition", example: "栄養のバランスを考える。", category: "noun" },
  { kanji: "文化", reading: "ぶんか", meaning: "culture", example: "日本の文化を学ぶ。", category: "noun" },
  { kanji: "伝統", reading: "でんとう", meaning: "tradition", example: "伝統を守る。", category: "noun" },
  { kanji: "歴史", reading: "れきし", meaning: "history", example: "歴史の本を読む。", category: "noun" },

  // Counters & Time expressions
  { kanji: "以上", reading: "いじょう", meaning: "more than, above", example: "三十人以上が参加した。", category: "expression" },
  { kanji: "以下", reading: "いか", meaning: "less than, below", example: "十度以下になる。", category: "expression" },
  { kanji: "以内", reading: "いない", meaning: "within", example: "一週間以内に届く。", category: "expression" },
  { kanji: "以外", reading: "いがい", meaning: "except, other than", example: "日曜日以外は忙しい。", category: "expression" },
  { kanji: "間に合う", reading: "まにあう", meaning: "to be in time", example: "電車に間に合った。", category: "expression" },

  // More useful N3 words
  { kanji: "交通", reading: "こうつう", meaning: "traffic, transportation", example: "交通が便利だ。", category: "noun" },
  { kanji: "事故", reading: "じこ", meaning: "accident", example: "交通事故に遭った。", category: "noun" },
  { kanji: "被害", reading: "ひがい", meaning: "damage, harm", example: "台風の被害が大きい。", category: "noun" },
  { kanji: "解決", reading: "かいけつ", meaning: "solution, resolution", example: "問題を解決する。", category: "noun" },
  { kanji: "目標", reading: "もくひょう", meaning: "goal, target", example: "目標を達成する。", category: "noun" },
  { kanji: "計画", reading: "けいかく", meaning: "plan, project", example: "計画を立てる。", category: "noun" },
  { kanji: "情報", reading: "じょうほう", meaning: "information", example: "正しい情報を得る。", category: "noun" },
  { kanji: "行動", reading: "こうどう", meaning: "action, behavior", example: "すぐに行動する。", category: "noun" },
  { kanji: "注目", reading: "ちゅうもく", meaning: "attention, notice", example: "世界が注目している。", category: "noun" },
  { kanji: "挑戦", reading: "ちょうせん", meaning: "challenge", example: "新しいことに挑戦する。", category: "noun" },
];
